@startuml 7章練習

title カレーを作る工程

start
:材料を用意する;

:お米を研ぐ;

:夕飯に丁度炊けるように炊飯器にセットする;
 
:野菜を洗う;

fork
:水の分量を測って鍋で湯を沸かす;
fork again
:材料を切る;
end fork

:沸騰したら鍋に材料を入れて煮込む;

:カレールーを入れて煮込む;

:お皿に盛り付ける;

:できらぁ！！！！;
stop

@enduml