@startuml 演習2-4
left to right direction

actor 利用者

usecase ログイン {
    - ID : 文字列
    - パスワード : 文字列
}

usecase 予約 {
    - 宿泊日 : 日付
    - 部屋タイプ : 文字列
    - 客室数 : 数値
    - 客室料金 : 金額
    ..> (キャンペーン価格で予約する) : <<extend>>
}

usecase (キャンペーン価格で予約する) {
    - キャンペーン期間 : 期間
}

usecase キャンペーン {
    - キャンペーン期間 : 期間
    - キャンペーン価格 : 金額
}

利用者 --> ログイン
利用者 --> 予約

予約 ..> ログイン : <<include>>
予約 --> (キャンペーン価格で予約する) : <<extend>>
(キャンペーン価格で予約する) ..> キャンペーン
@enduml
