@startuml 演習6-5-2
left to right direction

actor ユーザー
actor 光センサー
actor 左右モーター

rectangle ライントレーサーシステム {
  ユーザー -- (料金を入れラインの右境界線上を進む) 
  (料金を入れラインの右境界線上を進む)  -- 光センサー
  (料金を入れラインの右境界線上を進む)  -- 左右モーター
}
@enduml