@startuml 演習2-2
class 経営者 {
    - 給与 : 金額
    - 役職 : 文字列
}

class ホテル従業員 {
    - 給与 : 金額
    - 役職 : 文字列
}

class フロント係 {
    - 姓名 : 文字列
    - 雇用形態 : 文字列
}

class ルームサービス係 {
    - 姓名 : 文字列
    - 雇用形態 : 文字列
}

class レストラン係 {
    - 姓名 : 文字列
    - 雇用形態 : 文字列
}

経営者 <|-- ホテル従業員

フロント係 --|> ホテル従業員
ルームサービス係 --|> ホテル従業員
レストラン係 --|> ホテル従業員

@enduml
