@startuml 演習6-3 ユースケース図
ユーザ -> 予約システム : 接続
予約システム -> ユーザ : メニュー画面表示
ユーザ -> 予約システム : 予約と確認画面へ移動
予約システム -> ユーザ : 名前と電話番号入力要求
ユーザ -> 予約システム : 名前と電話番号入力
予約システム -> ユーザ : 登録ボタン押下
予約システム -> 予約システム : 登録情報記録
予約システム -> ユーザ : あなたの順番画面へ移動
ユーザ -> 予約システム : 名前か電話番号入力要求
ユーザ -> 予約システム : 名前か電話番号入力
予約システム -> ユーザ : 確認ボタン押下
予約システム -> ユーザ : あなたの順番画面へ移動
ユーザ -> 予約システム : 名前か電話番号入力要求
ユーザ -> 予約システム : 名前か電話番号入力
予約システム -> ユーザ : 取消ボタン押下
予約システム -> ユーザ : メニュー画面へ移動
予約システム -> ユーザ : 登録者番号表示（あなたの順番画面）
予約システム -> ユーザ : 現在の患者番号表示（今の順番画面）
予約システム -> 看護士 : 診察中の患者番号通知
看護士 -> 予約システム : 患者番号増加要求
@enduml