@startuml 演習3-1
class 派遣 {
- 社員ID
- 社員名
---
+ 社員ID設定（社員ID:int）:void
+ 社員ID取得（）:int
+ 社員名設定（社員名:String）:void
+ 社員名取得（）:String
}
class 契約社員 {
- プロジェクト名:String
---
+ プロジェクト名設定（プロジェクト名:String）:void
+ プロジェクト名取得（）:String
}
class 正社員 {
- 担当地域名:String
---
+ 担当地域名設定（プロジェクト名:String）:void
+ 担当地域名取得（）:String
}
社員 <|--down- 契約社員
社員 <|--down- 正社員
@enduml