@startuml 演習6-3 ユースケース図

[*] --> メニュー画面:接続
メニュー画面 --> 予約と確認画面 : 予約をする
予約と確認画面 --> 登録情報入力画面 : 登録ボタン押下
登録情報入力画面 --> あなたの順番画面 : 登録情報保存
予約と確認画面 --> あなたの順番画面 : 順番確認
予約と確認画面 --> メニュー画面 : 取消ボタン押下
あなたの順番画面 --> 今の順番画面 : 診察中の患者増加
今の順番画面 --> あなたの順番画面 : 診察完了

state メニュー画面 {
  [*] --> メニュー表示中
  メニュー表示中 --> 予約と確認画面 : 予約をする
  メニュー表示中 --> あなたの順番画面 : 順番確認
}

state 予約と確認画面 {
  [*] --> 予約確認中
  予約確認中 --> 登録情報入力画面 : 登録ボタン押下
  予約確認中 --> あなたの順番画面 : 順番確認
  予約確認中 --> メニュー画面 : 取消ボタン押下
}

state 登録情報入力画面 {
  [*] --> 情報入力中
  情報入力中 --> あなたの順番画面 : 登録ボタン押下
}

state あなたの順番画面 {
  [*] --> 順番表示中
  順番表示中 --> 今の順番画面 : 診察中の患者増加
}

state 今の順番画面 {
  [*] --> 順番表示中
  順番表示中 --> あなたの順番画面 : 診察完了
}

スマートフォン --> メニュー画面 : タッチ

@enduml