@startuml 演習2-1
left to right direction
skinparam packageStyle rect

actor 従業員
actor 上司

rectangle 出張申請 {
  従業員 --> (出張申請を作成する)
  (出張申請を作成する) --> (出張申請を提出する)
  (出張申請を提出する) --> 上司
  上司 --> (出張申請を承認する)
  (出張申請を承認する) --> (承認済みの出張申請を確認する)
  (承認済みの出張申請を確認する) --> 従業員
  従業員 --> (出張報告書を作成する)
  (出張報告書を作成する) --> (出張報告書を提出する)
  (出張報告書を提出する) --> 上司
  上司 --> (出張報告書を承認する)
  (出張報告書を承認する) --> (承認済みの出張報告書を確認する)
  (承認済みの出張報告書を確認する) --> 従業員
}

@enduml
